apiVersion: v1
kind: Service
metadata:
  name: mongodb-express-service
  labels:
    app: mongo
spec:
  type: LoadBalancer
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30000
      #30000-32767