apiVersion: apps/v1

kind: Deployment

metadata:
  name: myapp-deployment
  labels:
    app: myapp
    type: front-end

spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
        - name: myapp-pod
          image: nginx

  replicas: 8
  selector:
    matchLabels:
      type: front-end


kubectl get replicaset
kubectl create -f replica_set-definition.yml
kubectl delete replicaset myapp-replicaset
kubectl replace -f replica_set-definition.yml
kubectl scale -replicas=6 -f replica_set-definition.yml