apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: db-service
    app: voting-app

spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: voting-postgres-pod
    type: front-end

    