apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis-service
    app: voting-app

spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: voting-redis-pod
    type: front-end

    