apiVersion: apps/v1

kind: Deployment

metadata:
  name: voting-app-deployment
  labels:
    app: voting-app

spec:
  replicas: 1
  selector:
    matchLabels:
      app: voting-app-pod
      type: front-end

  template:
    metadata:
      name: voting-app-pod
      labels:
        app: voting-app-pod
        type: front-end

    spec:
      containers:
        - name: voting-app
          image: docker/example-voting-app-vote
          ports:
            - containerPort: 80
    
