apiVersion: v1
kind: Service
metadata:
  name: voting-result-service
  labels:
    name: voting-result-service
    app: voting-app

spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: voting-result-pod
    type: front-end

    